package biomons.bio.monsters;

import biomons.bio.monsters.Inimigo;
import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author pedro
 */
public class IndexInimigos extends javax.swing.JFrame {

    private int inimigoNum = 0;
    private int dificuldade;
    private List<Inimigo> inimigos = new ArrayList<Inimigo>();

    public void initInimigo(int inimigoNum) {
        //setNome e setDescrip com id Inimigo
        nomeArea.setText((inimigos.get(inimigoNum)).getNomeInimigo());
        descArea.setText((inimigos.get(inimigoNum)).getInfoInimigo());
    }

    public void addInimigos() {
        //adicionar inimigos com codeSala definido e dificulade menor ou igual a definida
        for (int i = 1; i <= dificuldade; i++) {
            try {
                DAO dao = new DAO();
                inimigos.add(dao.addInimigo(i));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void setDificuldade(int dificuldade) {
        this.dificuldade = dificuldade;
    }

    /**
     * Creates new form IndexInimigos
     */
    public IndexInimigos(int dificuldade) {
        initComponents();
        setDificuldade(dificuldade);
        addInimigos();
        initInimigo(inimigoNum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nomeArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        proxButtom = new javax.swing.JButton();
        antButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nomeArea.setColumns(20);
        nomeArea.setRows(5);
        jScrollPane1.setViewportView(nomeArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 60, 390, 90);

        descArea.setColumns(20);
        descArea.setRows(5);
        jScrollPane2.setViewportView(descArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 190, 330, 180);

        proxButtom.setBackground(new java.awt.Color(0, 0, 0));
        proxButtom.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\/PROXIMO_img.png")));
    proxButtom.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            proxButtomActionPerformed(evt);
        }
    });
    getContentPane().add(proxButtom);
    proxButtom.setBounds(690, 520, 260, 70);

    antButton.setBackground(new java.awt.Color(0, 0, 0));
    antButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\/ANTERIOR_img.png")));
    antButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            antButtonActionPerformed(evt);
        }
    });
    getContentPane().add(antButton);
    antButton.setBounds(210, 520, 290, 70);

    sairButton.setBackground(new java.awt.Color(0, 0, 0));
    sairButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\/SAIR_IMG.png"));
    sairButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            sairButtonActionPerformed(evt);
        }
    });
    getContentPane().add(sairButton);
    sairButton.setBounds(720, 280, 210, 90);

    jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\INDEX_INIMIGOS_BACKGROUND.png"));
    getContentPane().add(jLabel1);
    jLabel1.setBounds(50, 0, 1280, 720);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void antButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antButtonActionPerformed
        if (inimigoNum > 0) {
            inimigoNum--;
            initInimigo(inimigoNum);
        }
    }//GEN-LAST:event_antButtonActionPerformed

    private void proxButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxButtomActionPerformed
        if (inimigoNum < (dificuldade - 1)) {
            inimigoNum++;
            initInimigo(inimigoNum);
        }
    }//GEN-LAST:event_proxButtomActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexInimigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexInimigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexInimigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexInimigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antButton;
    private javax.swing.JTextArea descArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea nomeArea;
    private javax.swing.JButton proxButtom;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
