/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biomons.bio.monsters;

import java.util.concurrent.Semaphore;

/**
 *
 * @author pedro
 */
public class TelaResultados extends javax.swing.JPanel {
    private ResultadosListener listener;
    private Semaphore semaphore = new Semaphore(0);
    
    public void waitResultados()throws InterruptedException {
        semaphore.acquire();
    }
    
    public void initFunc(int acertos, int respondidas){
        textArea.setText("Parabéns você acertou " + acertos + " de " + respondidas+" questões respondidas!");
    }
    /**
     * Creates new form TelaResultados
     */
    public TelaResultados(int acertos, int respondidas) {
        initComponents();
        initFunc(acertos, respondidas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        sairButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(240, 60, 770, 190);

        sairButton.setBackground(new java.awt.Color(0, 0, 0));
        sairButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\SAIR_IMG (1).png"));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        add(sairButton);
        sairButton.setBounds(500, 570, 250, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\INDEX_INIMIGOS_BACKGROUND.png"));
        jLabel1.setPreferredSize(new java.awt.Dimension(1780, 720));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        if (listener !=null){
                listener.onSairClick();
        }
        semaphore.release();
    }//GEN-LAST:event_sairButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sairButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
