/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biomons.bio.monsters;

import java.util.concurrent.Semaphore;

/**
 *
 * @author pedro
 */
public class TelaInserirSala extends javax.swing.JPanel {
    private int codeSala;
    private SalaListener listener;
    private final Semaphore semaphore = new Semaphore(0);

    public int getCodeSala(){
        return codeSala;
    }
    
    public void waitSala() throws InterruptedException {
        semaphore.acquire();
    }
    
    /**
     * Creates new form TelaInserirSala
     */
    public TelaInserirSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        começar = new javax.swing.JButton();
        defaultSala = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        textField.setBorder(javax.swing.BorderFactory.createTitledBorder("Código da sala"));
        add(textField);
        textField.setBounds(80, 80, 700, 60);

        começar.setBackground(new java.awt.Color(0, 0, 0));
        começar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\BotaoIniciar.png"));
        começar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                começarActionPerformed(evt);
            }
        });
        add(começar);
        começar.setBounds(70, 230, 280, 70);

        defaultSala.setBackground(new java.awt.Color(0, 0, 0));
        defaultSala.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\INICIAR_SEM_SALA_IMG.png"));
        defaultSala.setText("  ");
        defaultSala.setPreferredSize(new java.awt.Dimension(230, 60));
        defaultSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultSalaActionPerformed(evt);
            }
        });
        add(defaultSala);
        defaultSala.setBounds(70, 350, 360, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\Painelprofessor.jpeg"));
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        add(jLabel1);
        jLabel1.setBounds(0, -10, 1290, 740);
    }// </editor-fold>//GEN-END:initComponents

    private void começarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_começarActionPerformed
        codeSala = Integer.parseInt(textField.getText());
        if (listener !=null){
                listener.onSalaClick();
        }
        semaphore.release();
    }//GEN-LAST:event_começarActionPerformed

    private void defaultSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultSalaActionPerformed
        codeSala = 1;
        if (listener !=null){
                listener.onSalaClick();
        }
        semaphore.release();
    }//GEN-LAST:event_defaultSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton começar;
    private javax.swing.JButton defaultSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
