/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biomons.bio.monsters;

import java.util.concurrent.Semaphore;


/**
 *
 * @author pedro
 */
public class TelaInterDificuldade extends javax.swing.JPanel {
    private InterContinuarListener listener;
    private final Semaphore semaphore = new Semaphore(0);
    private int codeSala;
    private int dificuldade;
    
    public void setCodeSala(int codeSala){
        this.codeSala=codeSala;
    }
    public void setDificuldade(int dificuldade){
        this.dificuldade = dificuldade;
    }
    
    public void waitInterContinuar() throws InterruptedException {
        semaphore.acquire();
    }
    
    /**
     * Creates new form TelaInterDificuldade
     */
    public TelaInterDificuldade(int codeSala,int dificuldade) {
        setCodeSala(codeSala);
        setDificuldade(dificuldade);
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continuarButton = new javax.swing.JButton();
        indexBioMons = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(null);

        continuarButton.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\CONTINUAR_IMG.png"));
        continuarButton.setBorderPainted(false);
        continuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonActionPerformed(evt);
            }
        });
        add(continuarButton);
        continuarButton.setBounds(429, 277, 192, 24);

        indexBioMons.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\BIODEX_IMG.png"));
        indexBioMons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexBioMonsActionPerformed(evt);
            }
        });
        add(indexBioMons);
        indexBioMons.setBounds(429, 313, 96, 24);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textArea.setRows(5);
        textArea.setText("Nivel Concluído");
        textArea.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setViewportView(textArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(429, 124, 344, 141);

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\TeladeLogin\\Painelprofessor.jpeg"));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1270, 750);
    }// </editor-fold>//GEN-END:initComponents

    private void continuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonActionPerformed
        if (listener != null) {
            listener.onInterContinuarClick();
        }
        semaphore.release();
    }//GEN-LAST:event_continuarButtonActionPerformed

    private void indexBioMonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexBioMonsActionPerformed
        new IndexInimigos(dificuldade).setVisible(true);
    }//GEN-LAST:event_indexBioMonsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarButton;
    private javax.swing.JButton indexBioMons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
